### ISSUE TITLE
Responder Not Seeing NBNS and LLMNR traffic

### ISSUE THREAD

**Issue by Fi1o** [lgandx/Responder#134]
![Screen Shot 2020-09-11 at 12 20 18 PM](https://user-images.githubusercontent.com/48696533/92949513-364bdf80-f429-11ea-8ba8-159d8bf155d2.png)

I have tried running Responder in python2 and python3, and verified with wireshark that I can see the NBNS and LLMNR traffic on the interface but Responder doesent seem to see any of it.

Ive also confirmed with netstat and other tools that everything is on the correct interface. All 3 windows workstations are properly connected to the domain controller and all in the same subnet as the Ubuntu box

**Comment by exploide** [comment]
Can confirm this behaviour. This happens since f84ad05e9a06f04a4491723ba4416f095ccbf370 by @nickyb.

I suspect the sockets to not accept broadcast traffic like NBNS/LLMNR/MDNS when an explicit bind address has been given. According to https://stackoverflow.com/a/32372627 either use the empty string as before or try to determine the correct broadcast address for the subnet the interface is listening on.

**Comment by lgandx** [comment]
Thanks for reporting this issue. 
This problem has been introduced by a recent merge and has now been fixed in the latest version.
Cheers
