### ISSUE TITLE
Target Improvements

### ISSUE THREAD

**Issue by aress31** [lgandx/Responder#143]
Could it be possible to add support for targeting specific IP ranges using CIDR, instead of the 192.168.0.1-255 notation?

Also being able to input a target file (one IP address/ranges per line) would be super welcome!

**Comment by lgandx** [comment]
You mean for clients from the 2000's who do not yet understand that a real threat is from anywhere on their internal range?
In order to replicate a real case scenario attack, pentests should be sold as goal oriented, not selective.
However, in a case where the client has some really highly sensitive servers and fears disruption or a "denied certification" red stamp, you can use the analyze mode ( -A ), study the queries, then configure Responder.conf's "RespondTo" setting accordingly ;)
