### ISSUE TITLE
SSL and Threads Errors

### ISSUE THREAD

**Issue by avi8892** [lgandx/Responder#206]
Hey, 

I׳m trying to use the new version, when I run it I get the following errors:

/home/kali/Desktop/Responder/./Responder.py:366: DeprecationWarning: setDaemon() is deprecated, set the daemon attribute instead
  thread.setDaemon(True)
/home/kali/Desktop/Responder/./Responder.py:256: DeprecationWarning: ssl.wrap_socket() is deprecated, use SSLContext.wrap_socket()
  server.socket = ssl.wrap_socket(server.socket, certfile=cert, keyfile=key, server_side=True)

**Comment by bonitopalabro** [comment]
I have the same problem.

**Comment by Zamanry** [comment]
Due to [Python 3.10](https://docs.python.org/3/whatsnew/3.10.html): "The following threading methods are now deprecated:
- threading.currentThread => [threading.current_thread()](https://docs.python.org/3/library/threading.html#threading.current_thread)
- threading.activeCount => [threading.active_count()](https://docs.python.org/3/library/threading.html#threading.active_count)
- threading.Condition.notifyAll => [threading.Condition.notify_all()](https://docs.python.org/3/library/threading.html#threading.Condition.notify_all)
- threading.Event.isSet => [threading.Event.is_set()](https://docs.python.org/3/library/threading.html#threading.Event.is_set)
- threading.Thread.setName => [threading.Thread.name](https://docs.python.org/3/library/threading.html#threading.Thread.name)
- threading.thread.getName => [threading.Thread.name](https://docs.python.org/3/library/threading.html#threading.Thread.name)
- threading.Thread.isDaemon => [threading.Thread.daemon](https://docs.python.org/3/library/threading.html#threading.Thread.daemon)
- threading.Thread.setDaemon => [threading.Thread.daemon](https://docs.python.org/3/library/threading.html#threading.Thread.daemon)
- (Contributed by Jelle Zijlstra in [gh-87889](https://github.com/python/cpython/issues/87889).)"

I may be able to fix this issue this week. Seems pretty straight forward.

**Comment by braintxx** [comment]
Same problem .

**Comment by lgandx** [comment]
This one has been fixed a few minutes ago.
Thanks for submitting this issue.
