### ISSUE TITLE
Fingerprint host Failed

### ISSUE THREAD

**Issue by paranoidninja** [lgandx/Responder#23]
I am currently using this responder on my nethunter with usb tethering on my oneplus1. I get a fingerprint host failed error whenever I use it with screen locked on my Win10Pro. It works with Screen unlocked too, but only as a MITM wpad method. It doesn't capture the NTLM hashes when the Windows is under workgroup.
![screenshot_20161219-202914](https://cloud.githubusercontent.com/assets/21009111/21339797/ebad41c4-c6a7-11e6-94fd-ae31cfd044de.png)

**Comment by julioauto** [comment]
This was happening to me too, similar use case. I commented out the try/except on fingerprint.py to get more info about what was failing. Turns out it was a connection timeout. I believe the firewall on the victim machine was preventing the connection (to port 445) on non-domain networks - which should include rogue USB tethering connections (assigned the 'Public' profile by default).

**Comment by lgandx** [comment]
Yes, SMB port is closed on the target computer ;)
